### ISSUE TITLE
Backspace and Delete are not working in Entity Editor text fields

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#2]
On Windows, both keys are just ignored. On Linux, Backspace works properly, but Delete prints a `DEL` character.

**Comment by skejeton** [comment]
Thank you for reporting windows related issues too, since I don't have access to that. Tophat's `getStr` doesn't work the same across platforms right now which is a Tophat issue, on linux it pushes backspace characters onto the character stream, but it doesn't do that on windows. Temporarily I'll fix this issue by checking if backspace was pressed.

**Comment by skejeton** [comment]
Hold on, wait, I already use backspace check. I think the issue is then that Tophat doesn't emit backspace on windows. I'll take a look.

**Comment by vtereshkov** [comment]
@skejeton Should I test anything on Windows?

**Comment by skejeton** [comment]
@vtereshkov Do it now, marek fixed backspace

**Comment by skejeton** [comment]
Closing this. It works now in Wine at least, aside from delete.
